version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: git clone https://github.com/microsoft/vcpkg
      - run: .\vcpkg\bootstrap-vcpkg.bat
      - run:
          name: Get Visual Studio Workloads
          command:  C:\"Program Files (x86)"\"Microsoft Visual Studio"\Installer\setup.exe modify `
                            --productId Microsoft.VisualStudio.Product.Community `
                            --channelId VisualStudio.17.Release `
                            --quiet `
                            --norestart `
                            --config .vsconfig
      - run: 
          name: Run Google Test
          command: |
            Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
            refreshenv 
            cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake"
            cmake --build build
            cd build
            ctest
