version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
      shell: powershell.exe -NoExit &{Import-Module \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"; Enter-VsDevShell -VsInstallPath \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\"}
    steps:
      - run: Write-Host 'Hello, CircleCI'
      - run:
          name: Run a vs dev shell via script
          shell: powershell.exe -NoExit -Command {& 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Launch-VsDevShell.ps1' -Arch amd64 -HostArch amd64}
          command: Write-Host 'Hello, CircleCI'
