version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: git clone https://github.com/microsoft/vcpkg
      - run: .\vcpkg\bootstrap-vcpkg.bat
      - run:
          name: Get Visual Studio Workloads
          command:  C:\"Program Files (x86)"\"Microsoft Visual Studio"\Installer\setup.exe modify `
                            --productId Microsoft.VisualStudio.Product.Community `
                            --channelId VisualStudio.17.Release `
                            --quiet `
                            --norestart `
                            --config .vsconfig
      - run:
          name: Save and load powershell profile
                # See https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3
          command: Copy-Item .circleci/powershell_profile.ps1 $PROFILE.CurrentUserAllHosts
      - run: 
          name: Run Google Test
          command: |
            cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake"
            cmake --build build
            cd build
            ctest
