version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Create powershell profile.
          command: Copy-Item .\Powershell_profile.ps1 $PROFILE.CurrentUserCurrentHost
      - run: Write-Host 'Hello, CircleCI'
      - run: 'Get-ChildItem env:'
      - run:
          name: Install Winget
          command: .circleci\install_winget.ps1
      - run: winget install --id koalaman.shellcheck --accept-source-agreements
      - run: $env:PATH
      - run: '& $env:LOCALAPPDATA\Microsoft\WinGet\Packages\koalaman.shellcheck_Microsoft.Winget.Source_8wekyb3d8bbwe\shellcheck -?'
