version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User' -y
      - run: git clone https://github.com/microsoft/vcpkg
      - run: .\vcpkg\bootstrap-vcpkg.bat
      - run: 
          name: Run Google Test
          command: |
            Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
            refreshenv 
            cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake"
            cmake --build build
            cd build
            ctest
