version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - run:
          name: Create powershell profile.
          command: Copy-Item .\Powershell_profile.ps1 $PROFILE.CurrentUserCurrentHost
      - run: Write-Host 'Hello, CircleCI'
      - run: Get-ChildItem env:
