version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: cd build && ctest
