version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
      shell: powershell.exe &{Import-Module \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"; Enter-VsDevShell -VsInstallPath \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\"}
    steps:
      - run: Write-Host 'Hello, CircleCI'
