version: 2.1

orbs: 
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Get Visual Studio Workloads
          command:  C:\"Program Files (x86)"\"Microsoft Visual Studio"\Installer\setup.exe modify `
                            --productId Microsoft.VisualStudio.Product.Community `
                            --channelId VisualStudio.17.Release `
                            --quiet `
                            --norestart `
                            --config .vsconfig
      - run:
          name: Install cmake
          command: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User' -y
      - run: 
          name: Run Google Test
          command: |
            Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
            refreshenv 
            cmake -S . -B build
            cmake --build build
            cd build
            ctest
